name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create local.properties from secrets
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" >> local.properties
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> local.properties
          echo "SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}" >> local.properties
          echo "API_URL=${{ secrets.API_URL }}" >> local.properties


      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload F-droid APK
        uses: actions/upload-artifact@v4
        with:
          name: app-fdroid-debug.apk
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk

      - name: Upload Play APK
        uses: actions/upload-artifact@v4
        with:
          name: app-play-debug.apk
          path: app/build/outputs/apk/play/debug/app-play-debug.apk